const shops = [
  {
    name: "La embajada",
    email: "Laembajada@hotmail.com",
    address: "Calle 2, Nueva Rosita",
    openNow: true,
    avgPrice: 85,
    rating: 4.5,
    code: "IsOpenAt",
    avgTime: 15,
    freeShipping: true,
    highLight: true,
    menu: [],
    schedule: {},
  },
  {
    name: "La estaca",
    email: "Laembajada@hotmail.com",
    address: "Sabinas, Coahuila",
    openNow: true,
    avgPrice: 85,
    rating: 4.5,
    code: "IsOpenAt",
    avgTime: 15,
    freeShipping: false,
    highLight: true,
    menu: [],
    schedule: {},
  },
  {
    name: "Mr.Boneless",
    email: "Laembajada@hotmail.com",
    address: "Comercial, Nueva Rosita",
    openNow: true,
    avgPrice: 85,
    rating: 4.5,
    code: "IsOpenAt",
    avgTime: 15,
    freeShipping: true,
    highLight: false,
    menu: [],
    schedule: {},
  },
  {
    name: "Mr.Boneless",
    email: "Laembajada@hotmail.com",
    address: "Comercial, Nueva Rosita",
    openNow: true,
    avgPrice: 85,
    rating: 4.5,
    code: "IsOpenAt",
    avgTime: 15,
    freeShipping: true,
    highLight: true,
    menu: [],
    schedule: {},
  },
];
export default shops;
