const shops = [
  {
    name: "La embajada",
    email: "Laembajada@hotmail.com",
    address: "Calle 2, Nueva Rosita",
    openNow: true,
    avgPrice: 85,
    menu: [],
    schedule: {},
  },
  {
    name: "La embajada",
    email: "Laembajada@hotmail.com",
    address: "Calle 2, Nueva Rosita",
    openNow: false,
    avgPrice: 75,
    menu: [],
    schedule: {},
  },
  {
    name: "La embajada",
    email: "Laembajada@hotmail.com",
    address: "Calle 2, Nueva Rosita",
    openNow: true,
    avgPrice: 85,
    menu: [],
    schedule: {},
  },
  {
    name: "La embajada",
    email: "Laembajada@hotmail.com",
    address: "Calle 2, Nueva Rosita",
    openNow: true,
    avgPrice: 85,
    menu: [],
    schedule: {},
  },
  {
    name: "La embajada",
    email: "Laembajada@hotmail.com",
    address: "Calle 2, Nueva Rosita",
    openNow: true,
    avgPrice: 85,
    menu: [],
    schedule: {},
  },
  {
    name: "La embajada",
    email: "Laembajada@hotmail.com",
    address: "Calle 2, Nueva Rosita",
    openNow: true,
    avgPrice: 85,
    menu: [],
    schedule: {},
  },
];
export default shops;
